output "vm_username" {
  value     = module.github_runner.vm_username
  sensitive = false
}

output "ssh_private_key" {
  description = "SSH private key generated by Terraform for connecting to the VM"
  value       = module.github_runner.ssh_private_key
  sensitive   = true
}